---

version: "3"

services:
  wospi:
    container_name: ${container_name}
    hostname: ${hostname}
    image: ${image}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CSV_DATA}:$HOMEDIR/csv_data:rw
      - ${WOSPI_CONFIG}:$HOMEDIR/wetter/config.py:r
      - ${BACKUP_DIR}:$HOMEDIR/backup:rw
      - ${NETRC_CONFIG}:$HOMEDIR/.netrc:r
      - ${HOME}/.ssh:$HOMEDIR/.ssh:r
      - ${TEMP_DIR}:/var/tmp:rw
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/vcio:/dev/vcio
    environment:
      TAG: "${TAG}"
      HOMEDIR: ${HOMEDIR}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_TOPIC_BASE: ${MQTT_TOPIC_BASE}
      TARGET: ${TARGET}
    restart: always
#
